### ISSUE TITLE
When building exe file getting Trojan virus using nexe

### ISSUE THREAD

**Issue by shaheem-khanzada** [nexe/nexe#976] opened 2022-03-31 13:21 UTC
<img width="1294" alt="image" src="https://user-images.githubusercontent.com/37620819/161064404-382515a8-ae9c-4c7b-9fff-adaa6238ef03.png">

**Comment by calebboyd** [comment] 2022-03-31 13:28
Duplicate of #945. You will need to sign your binary if you're shipping it to end users.

**Closed by calebboyd** 2022-03-31 13:28 UTC
