### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by centurions** [nexe/nexe#667] opened 2019-08-30 19:08 UTC
Error: https://github.com/nexe/nexe/releases/download/v3.0.0/windows-x64-10.16.3 is not available 

Hello . How can I fix this error ? 

Thank you .

**Comment by chandani-patel** [comment] 2019-09-06 08:25
I am also facing the same issue on linux with nodeJs 10.16.3.
Here are more details:
/opt # cat server.js | nexe
ℹ nexe 3.3.2
✔ Downloading pre-built Node.js
✔ Finished in 0.528s

Error: https://github.com/nexe/nexe/releases/download/v3.0.0/linux-x64-10.16.3 is not available, create it using the --build flag

See nexe -h for usage..

Works fine with latest nodejs version 12.9.1.

**Comment by chandani-patel** [comment] 2019-09-06 10:55
I fixed this by using node version 10.13.0
check the version suffix from https://github.com/nexe/nexe/releases to understand the node version support

**Comment by calebboyd** [comment] 2021-08-24 13:00
Duplicate of #754

**Closed by calebboyd** 2021-08-24 13:00 UTC
Labels: bug
