### ISSUE TITLE
FileVersion RC option not getting applied to the final EXE

### ISSUE THREAD

**Issue by oddmario** [nexe/nexe#866] opened 2021-02-24 15:14 UTC
**What happened**:
I built an EXE file with the `rc` option to change the default rc values. Everything gets replaced except for the `FileVersion` value (it still remains as the default Node.js value, which is the Node.js version)

**What you expected to happen**:
`FileVersion` should have been changed like the other RC values.

**How to reproduce it (as minimally and precisely as possible)**:
```js
const { compile } = require('nexe');
const path = require('path');

compile({
	input: './server.js',
	output: './app.exe',
	build: true,
	ico: path.resolve("./") + path.sep + "icon.ico",
	rc: {
		CompanyName: 'My company',
		ProductName: 'Sample server',
		FileDescription: '',
		FileVersion: '1,0,0,0',
		ProductVersion: '1,0,0,0',
		OriginalFilename: '',
		LegalCopyright: ''
	},
	clean: false,
	loglevel: 'verbose',
	temp: './build_temp'
}).then(() => {
	console.log('[+] Successful build.');
});
```

**Anything else we need to know?**:
It seems the `src/res/node.rc` gets patched correctly as specified here:
```cpp
BEGIN
    BLOCK "StringFileInfo"
    BEGIN
        BLOCK "040904b0"
        BEGIN
            VALUE "CompanyName", "My company"
            VALUE "ProductName", "Sample server"
            VALUE "FileDescription", ""
            VALUE "FileVersion", "1,0,0,0"
            VALUE "ProductVersion", "1,0,0,0"
            VALUE "OriginalFilename", ""
            VALUE "InternalName", "node"
            VALUE "LegalCopyright", ""
        END
    END
    BLOCK "VarFileInfo"
    BEGIN
        VALUE "Translation", 0x409, 1200
    END
END
```
However I am not sure why the final output still has the Node.js file version.

Also I tried different values for the `FileVersion` value like:
- `1,0,0,0`
- `1.0.0.0`
- `1.0.0`
- `1.0`
but the issue still persists in all the cases.

**Environment**:
- Platform(OS/Version): Windows Server 2019 x64
- Host Node Version: 14.15.3
- Target Node Version: 14.15.3
- Nexe version: 4.0.0-beta.17
- Python Version: 3.9.2

**Comment by oddmario** [comment] 2021-02-24 16:00
**Workaround:**
Using https://github.com/electron/node-rcedit to modify the file version after building the project using nexe

```js
const { compile } = require('nexe');
const path = require('path');
const rcedit = require('rcedit');

var INPUT_APP = "../server.js";
var OUTPUT_PATH = "../releases/app.exe";
var RC_COMPANYNAME = "Company name";
var RC_PRODUCTNAME = "Sample server";
var RC_FILEDESC = "";
var RC_FILEVER = "1.0.0.0";
var RC_PRODUCTVER = "1.0.0.0";
var RC_ORIGFILENAME = "";
var RC_LEGALCOPYRIGHT = "";

var CleanBuild = false; // Set to true if you want to remove the old stored Node.js binary build. You will have to set this to false again after the old build gets deleted by nexe.

compile({
	input: INPUT_APP,
	output: OUTPUT_PATH,
	build: true,
	ico: path.resolve("./") + path.sep + "icon.ico",
	rc: {
		CompanyName: RC_COMPANYNAME,
		ProductName: RC_PRODUCTNAME,
		FileDescription: RC_FILEDESC,
		FileVersion: RC_FILEVER,
		ProductVersion: RC_PRODUCTVER,
		OriginalFilename: RC_ORIGFILENAME,
		LegalCopyright: RC_LEGALCOPYRIGHT
	},
	clean: CleanBuild,
	loglevel: 'verbose',
	temp: './build_temp'
}).then(() => {
	// nexe fails to set the FileVersion using the rc option, so we use rcedit to set it.
	rcedit(OUTPUT_PATH, {
		'file-version': RC_FILEVER
	}).then(() => {
		console.log('[+] Successful build.');
	});
});
```

**Comment by calebboyd** [comment] 2021-08-24 13:18
Duplicate of #702

**Closed by calebboyd** 2021-08-24 13:18 UTC
Labels: bug
