### ISSUE TITLE
Use entrypoint from resources

### ISSUE THREAD

**Issue by sushant-at-nitor** [nexe/nexe#820] opened 2020-10-12 12:45 UTC
I use `@vercel/ncc` to compile the module in single file(index.js), I am also adding this to resources using `--resources` option

Can I use the `index.js` from resources as the entrypoint?

**Comment by calebboyd** [comment] 2020-10-12 12:47
`-i index.js` or `nexe index.js` is what you're after

**Comment by sushant-at-nitor** [comment] 2020-10-12 12:56
@calebboyd - thank you for quick response.

I tried this, but I still need to keep `bundle` along side the `my-app.exe`

`nexe -t x64-10.9.0 --resource "./bundle/**/*" -i bundle/index.js -o my-app.exe`

I wanted to check if there is any option so I don't have to provide `index.js` separately

**Comment by calebboyd** [comment] 2020-10-12 12:58
That shouldn't be necessary, do you have a minimal reproduction?

**Comment by sushant-at-nitor** [comment] 2020-10-12 13:01
Sure, I can provide you that. But if I copy the exe to some other location and when I try to execute I get following exception:

```
Error: Cannot find module '<some-other-path>\bundle\index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at Object.<anonymous> (e:\Projects\Qentinel\ws\qt-ps.exe:352:30)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at _third_party_main.js:37:36
    at NativeModule.compile (internal/bootstrap/loaders.js:271:7)
    at Function.NativeModule.require (internal/bootstrap/loaders.js:164:18)
    at internal/bootstrap/node.js:232:22
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

**Comment by sushant-at-nitor** [comment] 2020-10-13 12:39
@calebboyd - here is my directory structure. I would like to execute the `bundle/index.js` from the executable, if I execute it from `app` directory it works fine but if I copy executable to some other directory then it gives above error

app
- src/
- dist/
- bundle/
  - index.js
- package.json

**Comment by calebboyd** [comment] 2021-01-03 21:19
I can't reproduce this with the information here
Running nexe against a similar tree and moving it doesn't seem to cause issues

```
code/test > nexe app/bundle/index.js -o out -t 14.15.3
ℹ nexe 4.0.0-beta.15
✔ Already downloaded...
✔ Compiling result
✔ Entry: 'app/bundle/index.js' written to: out
✔ Finished in 0.113s
code/test > ./out
hello world
code/test > mv out ~/Desktop/out
code/test > cd ~/Desktop
~/Desktop > ./out
hello world
```

**Closed** 2021-09-27 14:01 UTC
Labels: more-information-needed

**Comment by sn0wst0rm** [comment] 2024-05-16 15:23
I have the same problem here. My main entry point for the app is index.js. I build everything (node 20.13.0) with next server.js --build, and it prodouces a bundled executable named 'server'. if I run the executable from the same folder it was created in, everything is fine, but if I try to cp it anywhere else in the disk and execute it, it crashes with:

`node:internal/fs/promises:636
  return new FileHandle(await PromisePrototypeThen(
                        ^

Error: ENOENT: no such file or directory, open '/path/to/server.js'
    at async open (node:internal/fs/promises:636:25)
    at async readFile (node:internal/fs/promises:1246:14)
    at async getSource (node:internal/modules/esm/load:46:14)
    at async defaultLoad (node:internal/modules/esm/load:137:34)
    at async ModuleLoader.load (node:internal/modules/esm/loader:396:7)
    at async ModuleLoader.moduleProvider (node:internal/modules/esm/loader:278:45)
    at async link (node:internal/modules/esm/module_job:78:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/path/to/server.js'
}`

@calebboyd try to bundle a file and then copy the executable somewhere completely different, like downloads and see if this also happens to you.

**Comment by YetAnotherGeorge** [comment] 2024-10-30 17:18
I have the same problem, in WSL - Ubuntu. Here is the entire project layout

- package.json:
```
{
  "name": "testapp",
  "version": "1.0.0",
  "description": "",
  "main": "./index.js",
  "scripts": {},
  "author": "",
  "license": "ISC",
  "dependencies": {
    "body-parser": "^1.20.2",
    "ejs": "^3.1.9",
    "express": "^4.18.2",
    "http-response-codes": "^1.0.4",
    "http-status-codes": "^2.2.0",
    "socket.io": "^4.6.1"
  }
}
```
- index.js
```
const fs = require('fs');
try {
   const fileContent = fs.readFileSync("public/someInfo.txt", { encoding: "utf-8" });
   console.log(`File content: ${fileContent}`);
} catch (ex) {
   console.log(`Error: ${ex.message}`);
}
```
- public/someInfo.txt is a text file
Node was installed via nvm, and when i run `nexe index.js --target 22.04 --build --resource "public/**/*" --verbose --output "dist/testApp" && cd dist && chmod +x testApp && ./testApp` i get 
```
Error: Cannot find module '/mnt/d/Backup/CS.Programming/Languages/WebDev.Node/NexeBuildTest/dist/index.js'
    at Function._resolveFilename (node:internal/modules/cjs/loader:1271:15)
    at Function._load (node:internal/modules/cjs/loader:1097:27)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:240:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:170:5)
    at node:internal/main/run_main_module:36:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```
