### ISSUE TITLE
/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found 

### ISSUE THREAD

**Issue by sagestudios** [nexe/nexe#654] opened 2019-07-18 19:17 UTC
**Is this a BUG or a FEATURE REQUEST?:** 
Not a bug not a feature

**What happened:**
I created exe flle on debain linux, file was created but when I try to run the exe it throwing an error. 

"/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found "

**What you expected to happen:**
should run without any error

**How to reproduce it (as minimally and precisely as possible):**
run debian version jessie, install latest g++, create exe for your node project

**Anything else we need to know?:**

**Environment**
gcc version 4.9.2 (Debian 4.9.2-10+deb8u2)

- Platform(OS/Version): debain jessie
- Host Node Version: 8.16.0
- Target Node Version: 8.16.0
- Nexe version:3.3.2
- Python Version: 2.7

**Comment by calebboyd** [comment] 2019-07-29 15:41
We need to figure out a version of linux that has a with a sufficiently new and still old enough glibc. I'm not sure what regular node uses but if you know that might help move this along.

You can always use the statically linked target. eg. `static-x64-8.16.0`

**Comment by luxmeter** [comment] 2019-11-14 16:29
hi @calebboyd are there other static linked versions too? 
I can't use async & await with 8.16 :'(

**Comment by dtenenba** [comment] 2019-11-17 17:30
FYI when I use a static target, I get the same error as the OP.

**Comment by abrekhov** [comment] 2020-01-30 08:00
I have same issue. Binary was built on CentOS 7
```
~$ (./index) /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./pcs-cluster-templater-js)
~$ strings /lib64/libstdc++.so.6* | grep GLIBC
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBC_2.3
GLIBC_2.2.5
GLIBC_2.14
GLIBC_2.4
GLIBC_2.3.2
```

**Comment by oxygen** [comment] 2020-06-15 16:52
What is the alpine static build name? 

I'm guessing its not the same as the newer glibc Linuxes.

**Comment by calebboyd** [comment] 2020-06-19 11:37
alpine-*-*

**Comment by calebboyd** [comment] 2020-06-19 11:39
Closing this as the issue relates to each of the machines the build was performed on and is not a bug.

See https://github.com/nodejs/node/blob/master/BUILDING.md for setting up a build environment

**Closed by calebboyd** 2020-06-19 11:39 UTC
