### ISSUE TITLE
Acorn Invalid number

### ISSUE THREAD

**Issue by vickylance** [nexe/nexe#438] opened 2017-12-22 19:50 UTC
This is a
 - [x] Bug Report
 - [ ] Feature Request
 - [ ] Other

<br/>
If this is a bug report, What are the steps to reproduce?

The fstream has a writer js file which has a weird JavaScript line which the Acron is unable to parse 

```
C:\Projects\web-projects\excel-ppt>nexe -t x86-9.3.0
i nexe 2.0.0-rc.22
Acorn error: Invalid number (16:17)
File: C:\Projects\web-projects\excel-ppt\node_modules\unzip2\node_modules\fstream\lib\writer.js

14  inherits(Writer, Abstract)
15
16  Writer.dirmode = 0777 & (~umask)
17  Writer.filemode = 0666 & (~umask)
18
19  var DirWriter = require("./dir-writer.js")
20    , LinkWriter = require("./link-writer.js")

Acorn error: Invalid number (16:17)
File: C:\Projects\web-projects\excel-ppt\node_modules\unzip2\node_modules\fstream\lib\writer.js

14  inherits(Writer, Abstract)
15
16  Writer.dirmode = 0777 & (~umask)
17  Writer.filemode = 0666 & (~umask)
18
19  var DirWriter = require("./dir-writer.js")
20    , LinkWriter = require("./link-writer.js")


- nexe 2.0.0-rc.22undefined
√ Compiling result
√ Entry: 'app.js' written to: app.exe
√ Finished in 11.613s
C:\Projects\web-projects\excel-ppt>

```

These are the 2 lines that the acron is unable to process,
**Writer.dirmode = 0777 & (~umask)
Writer.filemode = 0666 & (~umask)**

My configuration,
```
{
  "name": "excel-ppt",
  "version": "1.0.0",
  "description": "xlsx to ppt generation",
  "main": "app.js",
  "dependencies": {
    "chokidar": "^1.7.0",
    "excel": "^0.1.7",
    "pptxgenjs": "^1.10.0"
  },
  "devDependencies": {},
  "scripts": {
    "start": "node app.js",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [
    "excel",
    "xlsx",
    "ppt"
  ],
  "author": "Vignesh S",
  "license": "MIT"
}

```

<br/><br/>
Please also provide:

- Platform(OS/Version): Windows 10
- Host Node Version:9.3.0
- Target Node Version: 9.3.0
- Nexe version: 2.0.0-rc.22
- Python Version: 2.7.10

**Comment by hellais** [comment] 2018-01-11 21:02
Duplicate of https://github.com/nexe/nexe/issues/417

**Closed** 2018-11-29 17:04 UTC
Labels: bug, fixed-in-v3
