### ISSUE TITLE
Bundled exe doesnt work without node_modules present in the same folder

### ISSUE THREAD

**Issue by Hiws** [nexe/nexe#635] opened 2019-06-04 13:34 UTC
Hello.
I'm currently trying to bundle a simple script to list keys/values in the windows registry.
For this i use the NPM 'regedit', however it seems to fail when packaged with nexe and I'm unsure if it's something I'm doing wrong or not since this is the first time I'm using Nexe.

The error it's outputting is: 
```
events.js:174
      throw er; // Unhandled 'error' event
      ^

SyntaxError: Unexpected token I in JSON at position 0
    at JSON.parse (<anonymous>)
    at DestroyableTransform.module.exports.vbsOutputTransform [as _transform] (C:\snapshot\Registry Cleanup\node_modules\regedit\lib\helper.js:51:18)
    at DestroyableTransform.Transform._read (C:\snapshot\Registry Cleanup\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (C:\snapshot\Registry Cleanup\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:172:12)
    at doWrite (C:\snapshot\Registry Cleanup\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:237:10)
    at writeOrBuffer (C:\snapshot\Registry Cleanup\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:227:5)
    at DestroyableTransform.Writable.write (C:\snapshot\Registry Cleanup\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:194:11)
    at StreamSlicer.ondata (_stream_readable.js:689:20)
    at StreamSlicer.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
Emitted 'error' event at:
    at DestroyableTransform.onerror (_stream_readable.js:713:12)
    at DestroyableTransform.emit (events.js:189:13)
    at onwriteError (C:\snapshot\Registry Cleanup\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:250:10)
    at onwrite (C:\snapshot\Registry Cleanup\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:268:5)
    at WritableState.onwrite (C:\snapshot\Registry Cleanup\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:106:5)
    at afterTransform (C:\snapshot\Registry Cleanup\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:104:5)
    at TransformState.afterTransform (C:\snapshot\Registry Cleanup\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:79:12)
    at DestroyableTransform.module.exports.vbsOutputTransform [as _transform] (C:\snapshot\Registry Cleanup\node_modules\regedit\lib\helper.js:53:10)
    at DestroyableTransform.Transform._read (C:\snapshot\Registry Cleanup\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (C:\snapshot\Registry Cleanup\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:172:12)
```

**What you expected to happen:**
After bundling main.js, running the bundles exe file should list the values and keys at the given registry path.

**How to reproduce it (as minimally and precisely as possible):**
`nexe main.js --build`

**main.js**:
```javascript
const regedit = require('regedit')

regedit.list("HKCU\\Software\\Microsoft\\Windows NT\\CurrentVersion\\Devices")
.on('data', function(entry) {
  const values = entry.data.values;
  console.log('Values found: ', values)
})
.on('finish', function() {
  console.log('finished')
})
```

**Anything else we need to know?:**
The .exe file works if node_modules with regedit installed is present in the same folder as the .exe file. 

**Environment**

- Platform(OS/Version): Windows 10 build 1803
- Host Node Version: v11.11.0
- Target Node Version: v11.11.0
- Nexe version: v3.2.1
- Python Version: v2.7.15

**Comment by oonqt** [comment] 2019-06-04 23:32
The same thing has been happening to me, it was driving me nuts because I couldn't figure out what the problem was. It works fine until the node_modules folder isn't present.

**Comment by Gaalee** [comment] 2019-06-05 08:25
Same here, but is it not working as intended ?

**Comment by Hiws** [comment] 2019-06-05 10:28
> Same here, but is it not working as intended ?

It might be, but i honestly not sure.
I'm not sure if it's intended to bundle the modules with it, or if you simply have to supply them yourself with the bundled exe.

Which is why i asked the question here to get an answer whether it's working as intended or if i'm maybe doing something wrong.

**Comment by Gaalee** [comment] 2019-06-05 12:17
Then i am waiting the answer of @calebboyd aswell I would like to know about that.

**Comment by oonqt** [comment] 2019-06-05 20:24
I was thinking of using browserify to pack all my modules into a single file, but unfortunately that's out of the question since what I'm compiling relies on native modules. I've also had the same issues with [pkg](https://github.com/zeit/ncc) not including the modules that are required from node_modules

**Comment by timrspratt** [comment] 2019-06-05 21:10
I'm having the same issue with mac and linux binaries.

I've just tried adding `-r "./node_modules/**/*"` which seems to have added the files into the bundle (and increased the file size).

Wondering if this is correct, or if the nexe@next fixes this?

**Comment by oonqt** [comment] 2019-06-05 21:12
I'll try that in a bit, I hope that works as my project will be delayed until the node_modules folder will be included in the binary

**Comment by calebboyd** [comment] 2019-06-05 21:15
Are there packages in particular that are failing to load?

One could use [ncc](https://www.npmjs.com/package/@zeit/ncc) to provide a bundle to nexe. Any other dist artifacts produced there (eg native modules) will have to be shipped alongside the binary)

```
ncc build myapp.js
cat dist/myapp.js | nexe -o dist/myapp
```

**Comment by timrspratt** [comment] 2019-06-05 21:19
Thanks @calebboyd I will try that now.

I was bundling `express` and `body-parser` and it was failing to find express

**Comment by oonqt** [comment] 2019-06-05 21:19
Would it be possible for nexe to ever be able to include those native modules in the binary or is it not possible? I'm using a native module and I would like everything to be included into one single file.

**Comment by calebboyd** [comment] 2019-06-05 21:22
@timrspratt Thanks for the info.

@oonqt I don't know of a way to load a library not from the filesystem.

in node this is done with `process.dlopen`

**Comment by oonqt** [comment] 2019-06-05 21:38
[this](https://github.com/cdr/nbin) project seems like it provides support for native node modules

**Comment by Gaalee** [comment] 2019-06-05 22:33
Express is the one failing for me as well.

**Comment by calebboyd** [comment] 2019-06-10 21:46
@Hiws regedit [executes scripts](https://github.com/ironSource/node-regedit/tree/master/vbs) from the package directory using binaries on the windows machine.

Since those scripts (vbs, wsj) do not exist its failing. You'll have to ship those scripts with your binary.

**Comment by calebboyd** [comment] 2019-06-10 21:49
@oonqt 	nbin is just writing a temporary file and then reading it. You can do this as well. Nexe will/should not implicitly be doing this.

@timrspratt I can't replicate this issue with express and body-parser.. perhaps open a your own issue with more detail.

**Closed by calebboyd** 2019-06-10 21:49 UTC

**Comment by Hiws** [comment] 2019-06-10 22:00
> @Hiws regedit [executes scripts](https://github.com/ironSource/node-regedit/tree/master/vbs) from the package directory using binaries on the windows machine.
> 
> Since those scripts (vbs, wsj) do not exist its failing. You'll have to ship those scripts with your binary.

Thanks a lot for the answer.

**Comment by oonqt** [comment] 2019-06-10 22:10
> @oonqt nbin is just writing a temporary file and then reading it. You can do this as well. Nexe will/should not implicitly be doing this.
> 
> @timrspratt I can't replicate this issue with express and body-parser.. perhaps open a your own issue with more detail.

I know, I'm writing a temp file and then reading it for nexe, but that's not my issue. My issue is that nexe doesn't bundle native node modules into the executable.

**Comment by m4heshd** [comment] 2020-01-23 14:12
I had the same issue and finally realized it was because I've used a child process with more required modules inside that JS file.

**Comment by ashanoulu** [comment] 2025-02-27 09:20
In *pkg* we can include node modules using like below, (Node 18, pkg does not support Node 20 and up yet) 

`"pkg": {
    "assets": [
      "node_modules/sqlite3/lib/binding/napi-v6-win32-unknown-x64/node_sqlite3.node",
    ],
    "scripts": [
      "./dist/someJsFIles/*.js"
    ],
    "name": "my-app",
    "outputPath": "build"
  },`

But I have the same issue with nexe 4.0.0-rc.6
