### ISSUE TITLE
sharp nexe native

### ISSUE THREAD

**Issue by thbl** [nexe/nexe#342] opened 2017-06-29 17:35 UTC
Any one know how to use sharp with nexe ?
https://github.com/lovell/sharp

etc. how to add a native nodejs module

**Comment by calebboyd** [comment] 2017-06-29 18:49
@thbl There is no straight forward path for this right now. It will be possible in the next week or so if all goes well

**Comment by calebboyd** [comment] 2017-06-29 18:54
You can read through this if you want to give some of those approaches a try
https://github.com/nexe/nexe/issues/335

**Comment by thbl** [comment] 2017-06-29 19:02
@calebboyd thanks for you answer ! :)
if its only a question of 1-2 weeks i will wait instead of getting a headache :D

**Comment by thbl** [comment] 2017-07-10 17:59
@calebboyd  any news ? :)

**Comment by calebboyd** [comment] 2017-07-12 05:19
Workin' on it :)

**Comment by thbl** [comment] 2017-07-12 06:02
Cool can't wait ! :)

**Comment by calebboyd** [comment] 2017-07-15 06:34
@thbl @JamesMGreene #346 has a barebones example. I'll publish a beta after its merged and hopefully include bundling after a PR and a feature are added to fuse-box

**Comment by calebboyd** [comment] 2017-07-17 03:57
After 2.2.1-beta.6 of fusebox is out the [example](https://github.com/nexe/nexe/tree/master/examples/native-build) should have enough to get setup

**Comment by calebboyd** [comment] 2017-07-17 14:39
And, updated. Let me know!

**Comment by JamesMGreene** [comment] 2017-07-17 15:13
@calebboyd: So I was thinking it would be lovely if we could make nexe auto-detect native modules.  I know that some may still require additional configuration if they need to chain-load other DLLs and such but others would not.

Seems like we could use something like the [logic from inside of the `native-modules` module](https://github.com/juliangruber/native-modules/blob/1c8729403b01ab706729634fec34374980bec38b/index.js) to auto-detect all of the native modules installed and do something first-round configuration with that info.

**Comment by JamesMGreene** [comment] 2017-07-17 15:31
@calebboyd: Can we perhaps close this issue as a duplicate of #335? I'm getting confused commenting in both places. 😅

**Closed** 2017-07-17 18:48 UTC

**Comment by thbl** [comment] 2017-07-24 11:39
@calebboyd  should i just run this build file ?
https://github.com/nexe/nexe/blob/master/examples/native-build/build.js

or should i add somthing to it ? :S 
and if so could you please make an example with sharp :) sorry a little noob here ^^

**Comment by Abhishek150995** [comment] 2020-09-08 04:54
I too am facing a similar issue.

I have an application that interacts with C# Dll using 'edge-js'. Earlier I used electron to package the application so I used 'electron-edge-js' node modules, it worked perfectly fine. But now I want to switch to nexe packaging, but its generating error that it cannot find the 'edge-js' module at a particular location

Error: The specified module could not be found.
?\C:\Users..\Desktop.............\xyz\node_modules\edge-js\lib\native\win32\x64\12.13.0\edge_nativeclr.node

And when I explicitly place the node_modules at the location it generates different error

Error: Module did not self-register.

I am using the following command in my batch script

call nexe -i %~dp0AbcModule/"index.js" --resources %~dp0AbcModule/**/* -o %~dp0Abc\ExeName --vcBuild x64

same issue occurs even if I try with

call nexe -i %~dp0AbcModule/"index.js" --resources %~dp0AbcModule/**/* -o %~dp0Abc\ExeName

Node version: 12.13.1
Npm Version: 6.12.1
edge-js: "^13.0.1"
Windows 10 Pro 64bit OS

Please suggest! Thanks in advance
