### ISSUE TITLE
Getting error while executing

### ISSUE THREAD

**Issue by ksrawat** [nexe/nexe#420] opened 2017-11-06 19:34 UTC
This is a
 - [Y] Bug Report
 - [ ] Feature Request
 - [ ] Other

<br/>
If this is a bug report, What are the steps to reproduce?

1. Installed **npm prompt**
2. nexe <jsfile>
3. Now while executing getting following error

**return binding.readdir(pathModule._makeLong(path), options.encoding);**
```
//provide configuration here
```

<br/><br/>
Please also provide:

- Platform(OS/Version): Windows 10
- Host Node Version: v6.11.4
- Target Node Version:
- Nexe version: 2.0.0-rc.17
- Python Version: 3.7.0a2 - 2017-10-17

**Comment by calebboyd** [comment] 2017-11-08 05:38
duplicate of https://github.com/nexe/nexe/issues/393

**Closed by calebboyd** 2017-11-08 05:38 UTC
