### ISSUE TITLE
nexe not working for macOS with nodeTarget >= 14.0.0

### ISSUE THREAD

**Issue by sbittmann** [nexe/nexe#800] opened 2020-07-29 08:47 UTC
**What happened**:
NEXE not working with node-version >= 14.0.0. Just nodejs is started. EntryFile not called

**What you expected to happen**:
NEXE starts my entryFile

**How to reproduce it (as minimally and precisely as possible)**:
1. npm init
2. create File index.js with content "console.log('test');"
3. nexe index.js -t mac-x64-14.0.0
4. run generated file. Output is "Welcome to Node.js v14.0.0. Type ".help" for more information."

**Anything else we need to know?**:
"nexe index.js -t mac-x64-12.0.0" works on same project as expacted

**Environment**:
- Platform(OS/Version): macOS 10.15.4
- Host Node Version: v14.6.0
- Target Node Version: v14.0.0 - v14.5.0
- Nexe version: 3.37
- Python Version: no python

**Comment by calebboyd** [comment] 2020-07-29 13:33
Duplicate of #754 

This will become more of a priority as v14 approaches LTS

**Closed by calebboyd** 2020-07-29 13:33 UTC
Labels: bug
