### ISSUE TITLE
--target win32-x64-6.10.3 loads node version 7.0.0

### ISSUE THREAD

**Issue by FloMaetschke** [nexe/nexe#370] opened 2017-09-06 11:01 UTC
This is a
 - [ x] Bug Report
 - [ ] Feature Request
 - [ ] Other

<br/>
When compiling from cli nexe myapp.js -o result --target win32-x64-6.10.3 loads sources for 7.0.0 node version and not 6.10.3.
I have to specify 6.10.3 manually by --version 6.10.3 to get it to work.

<br/><br/>

- Platform(OS/Version): WIndows 10 x64
- Host Node Version: 7.0.0
- Target Node Version: 6.10.3
- Nexe version: 2.0.0-rc.2
- Python Version: 2.7.x

**Comment by calebboyd** [comment] 2017-09-07 03:33
weird... I can't replicate this

**Comment by FloMaetschke** [comment] 2017-09-07 11:13
Steps to reproduce.

build with 7.0.0 (or any other version)
there should be a download directory for it at: ./.nexe/7.0.0

after that start building with --target option e.g. --target win32-x64-6.10.3
It then says:

```
C:\Projekte\mde2\build>nexe backend.js -o mde2-server --build --target win32-x64-6.10.3
i nexe 2.0.0-rc.2
√ Source already downloaded
/ Compiling Node with arguments: nosign,release,x64
```

**Comment by calebboyd** [comment] 2017-09-14 18:30
This should be fixed

Still working on getting the build process ironed out so the number of prebuilts is limited

**Comment by calebboyd** [comment] 2017-09-25 18:44
Closing since I can no longer reproduce.
@FloMaetschke Let me know if you are still seeing problems

**Closed by calebboyd** 2017-09-25 18:44 UTC
Labels: bug
