### ISSUE TITLE
Unable to access script that begins in a child process

### ISSUE THREAD

**Issue by yapsang** [nexe/nexe#918] opened 2021-08-07 12:49 UTC
When I compile the application the file path changes so I am unable to access the script

I need the worker to have access to the script but the path has changed during the compile
```
taskRef["worker"] = new Worker(

      `const { parentPort ,workerData} = require('worker_threads')
      const FetchStats= require('./src/modules/sports/hockey.js')
      const startTasks = new ${FetchStats}()
      startTasks.getLists()`, {eval:true, workerData: task});
````
I am now unable to access the path './src/modules/sports/hockey.js' because the path has changed due to being compiled.

**Environment**:
- Platform(OS/Version): Windows
- Host Node Version: v14.16.1
- Target Node Version:
- Nexe version: 4.0.0
- Python Version:

**Comment by calebboyd** [comment] 2021-08-24 13:17
Duplicate of #680

**Closed by calebboyd** 2021-08-24 13:17 UTC
Labels: bug
