### ISSUE TITLE
Run without nodejs?

### ISSUE THREAD

**Issue by Alexander9673** [nexe/nexe#771] opened 2020-05-31 06:59 UTC
Is it possible to run this without nodejs installed on the system?

**Comment by AldieNightStar** [comment] 2020-06-06 10:20
Hi Alexander9673 :) No. Cause if you developing self-contained app in nodeJS, and wanted to pack it, you need this NodeJS app with all the NodeJS environment to make it work on computer, without NodeJS then.
Thank you :)

**Comment by calebboyd** [comment] 2020-06-06 11:57
I'm tracking this here: 
Duplicate of https://github.com/nexe/nexe/issues/543

**Closed by calebboyd** 2020-06-06 11:57 UTC
Labels: feature
