### ISSUE TITLE
Error: vcbuild.bat nosign release x64 exited with code: 1

### ISSUE THREAD

**Issue by SudryDev** [nexe/nexe#983] opened 2022-04-20 15:21 UTC
Hi, i tried nexe -i app.js -o dist -t windows-x64-16.14.2 --verbose --build --make 'V=2' and if it gives full files with ".cpp", ".cc" ect
i wait and i have:
```
√ Compiling Node with arguments: nosign,release,x64
√ Finished in 71.169s

Error: vcbuild.bat nosign release x64 exited with code: 1

See nexe -h for usage..
```
(NASM Installed, Python Installed, Visual Studio 2022 with Desktop C++ Installed)

**Comment by amiralam0** [comment] 2022-05-23 11:53
i am getting this issue too

**Comment by calebboyd** [comment] 2022-05-23 17:04
Closing as a duplicate of #968. Check out the [comment there](https://github.com/nexe/nexe/issues/968#issuecomment-1133800043)

If it seems to be a different issue, Please share the error message from the `--verbose` flag.

**Closed by calebboyd** 2022-05-23 17:04 UTC
