### ISSUE TITLE
SyntaxError: Invalid or unexpected token

### ISSUE THREAD

**Issue by jbyington** [nexe/nexe#814] opened 2020-09-17 02:43 UTC
**What happened**:

Compiled node/expressJS application using version 4.0.0-beta.14. 

`nexe app.js -t linux-x64-12.14.1 -n app.bin -r "config/**/*" -r "services/**/*" -r "services/gui/views/**/*" -r "services/gui/public/**/*"`

Compile is successful. When running binary, odd initial messages such as

`implifiedOperatorGlobalCache15CheckIfOperatorILNS0_16DeoptimizeReasonE18EEC1Ev`
or
`nal14WasmStackFrame11GetTypeNameEv`

and the consistent errors of (with various row/column) numbers 

```
SyntaxError: Invalid or unexpected token
    at Module._compile (internal/modules/cjs/loader.js:891:18)
    at internal/bootstrap/pre_execution.js:113:36
    at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:114:3)
    at internal/main/run_main_module.js:7:1
```

**What you expected to happen**:

Binary should run successfully. Running scripts without compiling with nexe works.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Platform(OS/Version): CentOS 8
- Host Node Version: 10.21.0
- Target Node Version: (Various) 
- Nexe version: 4.0.0-beta14
- Python Version: 2.7.17

**Comment by sinbargit** [comment] 2021-08-02 02:42
any update?

**Comment by calebboyd** [comment] 2021-08-02 12:32
Since there is no description here on how to reproduce this issue from the OP - I'm going to close this. If you can come up with a reproduction Please open a new issue!

![image](https://user-images.githubusercontent.com/5818726/127862391-213b2313-4eac-4be5-9cbf-ec7f349b92d0.png)

**Closed by calebboyd** 2021-08-02 12:32 UTC
Labels: bug
