### ISSUE TITLE
can't include http proxy library

### ISSUE THREAD

**Issue by lhy0512** [nexe/nexe#118] opened 2015-05-11 16:56 UTC
I include this library https://github.com/nodejitsu/node-http-proxy to my project. I can run nexe to create my single file successfully, but when I ran the binary file. It gives the following error at the bottom.

I then exclude the module by using the dynamic require technique mentioned in this page https://github.com/jaredallard/nexe, and put it alongside with the single file, it works then.

I'm pretty sure the issue comes from the one line: `var httpProxy = require('http-proxy');`
in my app.js.

New to node.js. Is it because this is an "native module" so I can't include it? It doesn't look like one.

``` js
nexe.js:25123
module.exports.createProxy = function createProxyServer(options) {
^
TypeError: Cannot set property 'createProxy' of undefined
at Array.call./home/selu/linguo-ui-lite/node_modules/http-proxy/lib/http-proxy.js.http (nexe.js:25123:30)
at initModule (nexe.js:29:11)
at nexe.js:31:64
at Array.call./home/selu/linguo-ui-lite/node_modules/http-proxy/index.js../lib/http-proxy (nexe.js:25095:18)
at initModule (nexe.js:29:11)
at nexe.js:31:64
at Array.call./home/selu/linguo-ui-lite/app.js.http (nexe.js:52:17)
at initModule (nexe.js:29:11)
at Array.forEach (native)
at nexe.js:39:8
```

**Comment by RainbowDashDC** [comment] 2015-05-11 17:00
will look into this, can't tell immediately what the issue is (but that may be due to the fact I am half asleep)

**Comment by lhy0512** [comment] 2015-05-11 17:03
Thanks for the quick response. let me know if you need more information. I'm very close to use nexe in my project after a few days of research except this issue.

**Comment by lhy0512** [comment] 2015-05-11 17:06
I'm using 
0.3.8 nexe
1.11.1 http-proxy
0.12.2 node.js

**Comment by RainbowDashDC** [comment] 2015-05-29 13:34
Sorry for the late response, been really busy. Not quite sure what's causing this.

**Comment by bdjibril** [comment] 2016-06-24 19:25
@lhy0512 how did you get this to work by using the dynamic require technique. It still does not work for me.

**Comment by bruce-one** [comment] 2016-09-09 04:15
Using `master` I'm still not able to `require('http-proxy')`, however as a workaround I instead required `http-proxy/lib/http-proxy/` instead.

Ie, this works (for me):

    'use strict';

    const http = require('http')

    const HttpProxyServer = require('http-proxy/lib/http-proxy/').Server
    const uglifyJs = require('uglify-js')
    const cleanCss = require('clean-css')
    const proxy = new HttpProxyServer({})

    const server = http.createServer( (req, res) => {
      proxy.web(req, res, { target: 'http://localhost:8080' })
    }).listen( () => console.log(`Listening on port ${server.address().port}`) )

Just in case anyone encounters this issue and wants a workaround :-)

**Comment by jaredallard** [comment] 2016-09-09 05:13
Huh, interesting work around!

On Thu, Sep 8, 2016, 21:15 bruce-one <notifications@github.com<mailto:notifications@github.com>> wrote:

Using master I'm still not able to require('http-proxy'), however as a workaround I instead required http-proxy/lib/http-proxy/ instead.

Ie, this works (for me):

'use strict';

const http = require('http')

const HttpProxyServer = require('http-proxy/lib/http-proxy/').Server
const uglifyJs = require('uglify-js')
const cleanCss = require('clean-css')
const proxy = new HttpProxyServer({})

const server = http.createServer( (req, res) => {
  proxy.web(req, res, { target: 'http://localhost:8080' })
}).listen( () => console.log(`Listening on port ${server.address().port}`) )


Just in case anyone encounters this issue and wants a workaround :-)

**Comment by bruce-one** [comment] 2016-09-09 23:47
Hmm, it looks like the issue is caused within the `http-proxy/lib/http-proxy.js` file; if `httpProxy = require('./http-proxy/')` is changed to `httpProxy = require('./http-proxy/index.js')` it seems to work correctly? :-s

**Comment by bruce-one** [comment] 2016-09-13 04:15
For anyone playing along at home, there's an issue in the `resolve` library which is the cause of this issue in nexe (because `resolve` is used by browserify for the bundling):

https://github.com/substack/node-resolve/issues/51

**Comment by calebboyd** [comment] 2017-08-05 03:16
Closing!

**Closed by calebboyd** 2017-08-05 03:16 UTC
Labels: important, in progress
