### ISSUE TITLE
log4js dependency issue.

### ISSUE THREAD

**Issue by Zendrex** [nexe/nexe#996] opened 2022-06-09 17:42 UTC
Was looking into adding log4js into my application, however I noticed that one of its dependencies called [flatted ](https://www.npmjs.com/package/flatted)doesn't get compiled into the executable and fails to run outside of the project directory. Unsure as to why, however here is the stack trace plus the code that I used to test it out.

Stack:
```
node:internal/modules/cjs/loader:942
  throw err;
  ^

Error: Cannot find module 'flatted'
Require stack:
- C:\Users\Zendrex\node_modules\log4js\lib\LoggingEvent.js
- C:\Users\Zendrex\node_modules\log4js\lib\clustering.js
- C:\Users\Zendrex\node_modules\log4js\lib\appenders\index.js
- C:\Users\Zendrex\node_modules\log4js\lib\log4js.js
- C:\Users\Zendrex\node_modules\@aetherjs\framework\dist\index.js
- C:\Users\Zendrex\Desktop\New folder\build\index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:939:15)
    at Module._load (node:internal/modules/cjs/loader:780:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\Zendrex\node_modules\log4js\lib\LoggingEvent.js:1:17)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Module._load (node:internal/modules/cjs/loader:827:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\Zendrex\\node_modules\\log4js\\lib\\LoggingEvent.js',
    'C:\\Users\\Zendrex\\node_modules\\log4js\\lib\\clustering.js',
    'C:\\Users\\Zendrex\\node_modules\\log4js\\lib\\appenders\\index.js',
    'C:\\Users\\Zendrex\\node_modules\\log4js\\lib\\log4js.js',
    'C:\\Users\\Zendrex\\node_modules\\@aetherjs\\framework\\dist\\index.js',
    'C:\\Users\\Zendrex\\Desktop\\New folder\\build\\index.js'
  ]
}
```

Code Block (precompiled)
```
import log4js from 'log4js';

// Logger Config
log4js.configure({
	appenders: {
		out: {
			type: 'stdout',
			layout: {
				type: 'pattern',
				pattern: '%[%d{hh:mm:ss} %p%] %[[%c]%] %m',
			},
		},
	},
	categories: { default: { appenders: ['out'], level: 'debug' } },
});

export function getLogger(_name?: string) {
	return log4js.getLogger(_name);
}
```

**Comment by calebboyd** [comment] 2022-06-09 17:51
This is a duplicate of #414 You can use the workaround described there.

https://github.com/nexe/nexe/issues/414#issuecomment-337386052

**Comment by Zendrex** [comment] 2022-06-10 07:04
> This is a duplicate of #414 You can use the workaround described there.
> 
> [#414 (comment)](https://github.com/nexe/nexe/issues/414#issuecomment-337386052)

I've attempted the workaround you provided, however that doesn't seem to resolve the issue, even when copy-pasting the solution.

I tried both with import and require as well.

My workflow is typescript -> tsup -> nexe

**Comment by OmgImAlexis** [comment] 2022-06-16 05:27
Im using nexe with tsup and didn't do anything special when using log4js. Have you made sure to install `log4js` as a devDep so tsup inlines it?

**Closed** 2022-07-26 14:02 UTC
Labels: more-information-needed
