### ISSUE TITLE
require Mongodb gives error:No such native module ./binary_parser

### ISSUE THREAD

**Issue by exhesham** [nexe/nexe#192] opened 2016-03-03 02:41 UTC
Hi,

My nodejs code is the next line:
`var Mongo = require('mongodb').`

When I run the nexe, i get the error below:

> node.js:932
>       throw new Error('No such native module ' + id);
>       ^
> 
> Error: No such native module ./binary_parser
>     at NativeModule.require (node.js:932:13)
>     at s (nexe.js:1:176)
>     at nexe.js:1:367
>     at nexe.js:29613:17
>     at Array.forEach (native)
>     at Object.__dirname.66../bson (nexe.js:29612:15)
>     at s (nexe.js:1:316)
>     at nexe.js:1:367
>     at Object.__dirname.40../utils (nexe.js:18827:12)
>     at s (nexe.js:1:316)

I am using:
nexe 5.5.0
nodejs version:5.6

I tried adding mongodb to nexe.browserify.requires in nexe package.json but it didn't help!

Could you please help me with this issue.
Many thanks for the great project

**Comment by jaredallard** [comment] 2016-03-07 20:30
Hi, try adding it to `nexe.browserify.exclude(s)`

**Comment by exhesham** [comment] 2016-03-08 07:36
Thanks for the response. However, how do i configure that? in the package.json? if so, is this the correct syntax? because it is not working for me:
`"browserify": {
        "requires": [],
        "excludes": ["mongodb","/path/to/node_modules/mongodb"],
        "paths": []
    },
    "temp": "src"`

Thanks in advance.

**Comment by jaredallard** [comment] 2016-03-08 18:51
try 

```json
{
....
"browserify": {
"excludes": ["binary_parser"]
}
...
}
```

**Comment by 94kamal** [comment] 2016-03-29 07:06
I have made the following changes to package.json file.

"nexe": {
    "input": "./bin/nexe",
    "output": "nexe^$",
    "temp": "src",
    "browserify": {
        "requires": [],
        "excludes": ["binary_parser"],
        "paths": []
    },
    "runtime": {
        "framework": "node",
        "version": "5.8.0",
        "js-flags": "--use_strict",
        "ignoreFlags": true
    }

Still its not working and I am getting the same error.

**Comment by sandeep-pal** [comment] 2016-05-06 16:14
Is there any update on this issue? Running into the same problem.

**Comment by taiffu** [comment] 2016-08-13 17:47
Have some one found solution for this? I have same problem when trying to use nexe

throw new Error('No such native module ${id}'); 
Error: No such native module ./node-mongodb-native

**Comment by thekiba** [comment] 2016-08-13 19:54
@taiffu, hello.

I use `browserify.requires` for resolving same problems and with `mongodb` too. But  that option don't worked for me and i was be fixed that. To check #243 and #244. 

And you have another way. You can to fix `require` in package, but it is not a good, because you will be have problems with them updating.

**Comment by pavithra-doraiswamy** [comment] 2016-08-19 21:57
Hi,

I still see this error when I try to excecute the binary generate with nexe.

bootstrap_node.js:435
      throw new Error(`No such native module ${id}`);
      ^

Error: No such native module ./node-mongodb-native
    at NativeModule.require (bootstrap_node.js:435:13)
    at s (nexe.js:1:176)
    at nexe.js:1:367
    at Object.__dirname.86../browser (nexe.js:11910:12)
    at s (nexe.js:1:316)
    at nexe.js:1:367
    at Object.__dirname.106../drivers (nexe.js:20452:16)
    at s (nexe.js:1:316)
    at nexe.js:1:367
    at Object.__dirname.98.../package.json (nexe.js:12442:14)

**Comment by jaredallard** [comment] 2016-08-19 22:06
Hey everyone, sorry for my absence on this. This is a dupe of a lot of other issues. It's a problem with browsify. It's fixed in v2 but v2 isn't anywhere near production ready, nor can I really back port changes.

A solution is to use master branch which should have the pr that somewhat fixes the behaviour of this, but requires node_modules. Which isn't inherently a fix. Finding it very hard to work in this while I do my day job.

On Fri, Aug 19, 2016, 14:57 pavithra-doraiswamy <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi,

I still see this error when I try to excecute the binary generate with nexe.

bootstrap_node.js:435
throw new Error(No such native module ${id});
^

Error: No such native module ./node-mongodb-native

at NativeModule.require (bootstrap_node.js:435:13)
at s (nexe.js:1:176)
at nexe.js:1:367
at Object.__dirname.86../browser (nexe.js:11910:12)
at s (nexe.js:1:316)
at nexe.js:1:367
at Object.__dirname.106../drivers (nexe.js:20452:16)
at s (nexe.js:1:316)
at nexe.js:1:367
at Object.__dirname.98.../package.json (nexe.js:12442:14)

**Comment by qlux** [comment] 2016-09-01 16:30
Hi,

Testing with the _express-test_ project inside the _test_ project seems to give the appropriate behavior. By adding
`var mongodb = require("mongodb")`
inside the _app.js_ and adding
`"browserify": {
      "requires": [],
      "excludes": ["mongodb"],
      "paths": []
    },`
inside _package.json_, the binary seems to look for external dependencies inside node_modules.

- If no _node_modules_ directory is present, it gives:
`Error: ENOENT: no such file or directory, lstat '/workspace/nexe/test/express-test/node_modules'`

- With the correct dependencies installed inside node_modules, everything works correctly

>I did not have this behavior with my other test (node v6.5) but it seems that in this project, the settings give the correct behavior.

**Comment by CKarper** [comment] 2016-09-01 16:32
If you're excluding mongodb from packaging, then wouldn't you expect it to
not work unless you've installed it?

**Comment by qlux** [comment] 2016-09-01 17:20
As **exhesham** tried, excluding the package was not working correctly because the binary exported was not looking for the module inside the node_modules folder and I have the same behavior with the last version of node+nexe.

With node v5.10, as in the _express-test_ project, using **exclude** and installing the package inside node_modules actually works.

**Comment by CKarper** [comment] 2016-09-01 17:21
Gotcha, thanks.

**Comment by qlux** [comment] 2016-09-01 21:19
It seems I am mistaken: it is not related to this project in particular because I was unable to compile it and have the same result on another machine (reusing a temp folder from another compilation).
It seems to be related to the temp folder indeed:
- Moving the project to another machine and compile it with another _tmp_ folder gives:
`Error: No such native module mongodb`
- Moving the project and the _tmp_ folder to another machine and compile it using this tmp folder works correctly

Maybe the whole compilation including all the cc files has to be done for each project ?

**Comment by calebboyd** [comment] 2017-09-04 22:32
Closing -- Please comment if you're still being blocked by this issue
Using nexe 2.0.0-rc.2

index.js
```javascript
var mongodb = require('mongodb');
```
Building with
`nexe -o out`
Yields no errors when executing. `./out` or `./out.exe`

**Closed by calebboyd** 2017-09-04 22:32 UTC
