### ISSUE TITLE
Problem with iconv-lite decoding

### ISSUE THREAD

**Issue by meilon** [nexe/nexe#301] opened 2017-02-12 12:19 UTC
Hi,

I'm using Dissolve to load a binary file and iconv-lite to decode strings. Using it via `node app.js` works fine, but when I bundle it up using nexe, I get the following error when starting my app:

```
nexe.js:5554
        throw new Error("Encoding '"+codecOptions.type+"' has incorrect 'chars' (must be of len 128 or 256)");
        ^

Error: Encoding '_sbcs' has incorrect 'chars' (must be of len 128 or 256)
    at new SBCSCodec (nexe.js:5554:15)
    at Object.getCodec (nexe.js:8287:25)
    at Object.getDecoder (nexe.js:8309:23)
    at Object.decode (nexe.js:8227:25)
    at Dissolve.string.buffer.tap (nexe.js:34:26)
    at Dissolve._transform (nexe.js:231:16)
    at Dissolve.Transform._read (nexe.js:3520:10)
    at Dissolve.Transform._write (nexe.js:3508:12)
    at doWrite (nexe.js:3826:12)
    at writeOrBuffer (nexe.js:3813:5)
```

I'm doing some encoding later and it works. What is going wrong?

**Comment by calebboyd** [comment] 2017-04-09 22:24
Could you provide the minimal code and configuration needed to reproduce this?

**Comment by pichulines** [comment] 2017-04-20 14:33
Same issue happens to me... I'm compiling with nexe a project which involves iconv-lite and I'm getting the same error when running the executable generated by nexe...

The script throwing the error is [sbcs-codec.js](https://github.com/ashtuchkin/iconv-lite/blob/master/encodings/sbcs-codec.js) which is not capable of managing special chars included in codecOptions object.
While I'm getting the following codecOptions when running my uncompiled project:
`codecOptions: {
  "type": "_sbcs",
  "chars": "€�‚ƒ„…†‡ˆ‰Š‹Œ�Ž��‘’“”•–—˜™š›œ�žŸ ¡¢£¤¥¦§¨©ª«¬­®¯°±²³´µ¶·¸¹º»¼½¾¿ÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖ×ØÙÚÛÜÝÞßàáâãäåæçèéêëìíîïðñòóôõö÷øùúûüýþÿ",
  "encodingName": "windows1252"
}`
The special chars property seems to be initialized to empty when running the nexe executable:
`codecOptions: {
  "type": "_sbcs",
  "chars": "",
  "encodingName": "windows1252"
}`

I'm not using the iconv-lite lib straight forward but through the mssql lib, so I don't unsderstand well the code. Anyway something related with the character encoding is different when I run my project as a nexe executable.
I hope this helps to clarify the issue.
Thanks.

**Comment by reinaldorauch** [comment] 2017-07-14 04:58
+1

**Comment by calebboyd** [comment] 2017-07-17 19:30
This should be fixed. Please try `nexe@beta`

**Closed** 2017-09-04 19:56 UTC
Labels: more-information-needed, needs-reproduction
