### ISSUE TITLE
Cannot find module 'default/.app.js'

### ISSUE THREAD

**Issue by mika-fischer** [nexe/nexe#385] opened 2017-09-25 09:36 UTC
This is a
 - [x] Bug Report
 - [ ] Feature Request
 - [ ] Other
<br/>
Steps to reproduce:

```
> npm init -y
> npm i -S nexe
> touch app.js (or .ts)
> nexe app.js (or .ts)
> app.exe
module.js:491
    throw err;
    ^

Error: Cannot find module 'default/.app.js'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at s (C:\Users\mfischer\src\tests\nexe-test-2\app.exe:13:1793)
    at c (C:\Users\mfischer\src\tests\nexe-test-2\app.exe:13:2842)
    at Function.r.import (C:\Users\mfischer\src\tests\nexe-test-2\app.exe:13:3747)
    at d (C:\Users\mfischer\src\tests\nexe-test-2\app.exe:10:15)
    at Object.<anonymous> (C:\Users\mfischer\src\tests\nexe-test-2\app.exe:13:1)
    at Module._compile (module.js:573:30)
```

<br/>

- Platform(OS/Version): Windows 10
- Host Node Version: 8.4.0
- Target Node Version: 8.4.0
- Nexe version: 2.0.0-rc6
- Python Version: 2.7.14

**Comment by calebboyd** [comment] 2017-09-25 13:29
You'll have to give me a little more info. I can' t reproduce this

![image](https://user-images.githubusercontent.com/5818726/30810691-84c093bc-a1cb-11e7-888d-5dfef8e37c58.png)

**Comment by mika-fischer** [comment] 2017-09-25 13:32
What info can I provide? Is there a way to enable debug out or view the contents of the package that nexe puts together?

**Comment by calebboyd** [comment] 2017-09-25 13:37
`--debugBundle app.bundle.js`

**Comment by mika-fischer** [comment] 2017-09-25 13:46
Oh, I see the issue now, it's a path parsing issue... Try `nexe .\app.js`... It seems the windows-style backslashes as path separators are not converted into slashes for node module resolution but instead treated as special characters. In another case I get from `nexe .\build\app.js` the error `Error: Cannot find module 'default/uildapp.js'` ('\b' -> bell?, '\a' -> a, path separators missing).

**Comment by calebboyd** [comment] 2017-09-25 14:06
hmm, thanks for finding that. I'll pass it through `path.relative(cwd, input)`. I suppose it may also work if you escaped the `\`

**Comment by palavrov** [comment] 2017-09-27 10:59
I got similar problem because of this change

https://github.com/nexe/nexe/commit/8f96b2bca9913a3712020501de05843f8ec765ad

`require.resolve(toAbsolute(argv.i))` doesn't work for relative paths when nexe is local dev dependency. Rolling back to v1.1.2 solves the problem.

**Comment by calebboyd** [comment] 2017-09-27 18:39
@palavrov The commit you referenced is from the v1 branch. 

Did you try updating to v2?

**Comment by calebboyd** [comment] 2017-09-27 19:14
the OP's issue has beenf fixed in `nexe@beta`

Closing. 

@palavrov if you have another problem please open new issue with appropriate detail.

**Closed by calebboyd** 2017-09-27 19:14 UTC
Labels: bug

**Comment by palavrov** [comment] 2017-09-27 19:35
Indeed it is a different issue - the similarity is just the error text "Cannot find module ..." for the start script given with CLI -i parameter. See #389

**Comment by calebboyd** [comment] 2017-10-04 13:24
@mika-fischer I saw you were working on a set of bindings for a windows service.

I'm working on addressing this as well via a nexe plugin. While it won't land with 2.0 It will probably come later, I'd love to get your feedback on potential approaches there. Or in general, features you might see are missing in nexe.

**Comment by mika-fischer** [comment] 2017-10-04 14:53
@calebboyd I'm happy to give some feedback, because we want to bundle our application for deployment to customers. And there are some issues with using nexe for this.

I don't fully understand what nexe does exactly regarding native modules and now the windows service functionality. But AFAICT things are extracted from the executable at runtime. This is an issue because if the application is installed into %ProgramFiles% on Windows, the application is not allowed to write to that directory!

So at the minimum there needs to be a possibility during installation to extract the extra stuff so that after installation no write access to %ProgramFiles% is necessary. Or - and I would prefer that - a possibility to pre-extract all these things during bundling so that they can just be deployed alongside the executable in the first place.

Regarding the winsw approach, that's probably fine for most use-cases (apart from issues mentioned above). However, we prefer the simplicity (only one process) and flexibility (command line flags for the service process, command line flags to install the service, etc.) with the approach using a native addon. I think both can co-exist quite well :-)

Since cluster-mode is supported now, I'll give nexe another try and see if I run into more issues.

**Comment by calebboyd** [comment] 2017-10-04 15:29
@mika-fischer Great feedback. I appreciate you elaborating on your use case. We are currently running 100s of deployments but haven't run into any problems like you've described. And they sound like valid issues that I would like to address.

Can I ask how you normally perform installation? Do you rely on the binary itself or do you package it in an installer.

Regarding cluster and fs additions. They're available in `nexe@beta`

**Comment by mika-fischer** [comment] 2017-10-04 15:44
We package the app using NSIS and the installer installs it into `%ProgramFiles%\ProductName`.

Since Windows Vista, the `%ProgramFiles%` directory is protected from modification by processes without elevated privileges. I haven't actually tried (because I'm still struggling to get a functioning nexe package of the app), but I suspect, the runtime unpacking will cause problems.

Same thing on Linux if you install as root into `/opt/Application` and run the app as a different user (which you should!). You won't have permissions to extract the files there, either.

**Comment by calebboyd** [comment] 2017-10-04 15:52
Yeah, thats a big caveat, thanks for bringing it to my attention. -- It should be fairly simple to solve though I think.

Feel free to open an issue for any other issues you're having.

**Comment by calebboyd** [comment] 2017-10-05 05:35
created https://github.com/nexe/nexe/issues/401
